name: Docker Image CI # name of the workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest # image used to build the project

    steps:
    - uses: actions/checkout@v3 # checkout the code
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 # configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # pull the credentials from the secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # pull the credentials from the secrets
        aws-region: us-east-2 # region of ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1 # login to ECR

    - name: Build and Push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr-repo-1 # name of the ECR repository
        IMAGE_TAG: latest
      run: | # build the docker image and push to ECR
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"